### ISSUE TITLE
Import Error when running script as from QuPath CLI

### ISSUE THREAD

**Issue by estellenassar** [BIOP/qupath-biop-extensions#8]
Hi,

When running the `appendCcfCoordinatesToDetections.groovy` script headlessly with the QuPath CLI command 

```
"QuPath-0.2.3 (console).exe" script -p=myproject.qppath appendCcfCoordinatesToDetections.groovy
```

We get an import error message for the imglib2! 

```
It looks like you have tried to import a class 'net.imglib' that doesn't exist!
MultipleCompilationErrorsException at line 9: startup failed:
Script1.groovy: 10: unable to resolve class net.imglib2.RealPoint
 @ line 10, column 1.
   import net.imglib2.RealPoint
```

The script works fine in the QuPath GUI, though.  How do we get this to work with the CLI?

Best wishes,

Estelle & Nick

**Comment by NicoKiaru** [comment]
Oh, whoah. No idea! Maybe @petebankhead has an idea ? The classpath in the GUI is not the same as in the CLI ?

**Comment by estellenassar** [comment]
That could be. We're new to the java world, is there a way to add a classpath in the script?

**Comment by petebankhead** [comment]
See https://github.com/qupath/qupath/pull/665#issuecomment-919283605 for a workaround (sounds like a bug in QuPath - not sure yet why it is happening).

**Comment by petebankhead** [comment]
Actually, I'm not sure if it's a QuPath bug. First you need to drag any necessary jars onto QuPath when it is running interactively, then add them to an extensions directory when prompted (you can specify the location if needed).

Then the jars should be available on the classpath when run either interactively or from a command line.

I've just copied the imglib2 jar to my QuPath extensions directory, and run this on my Mac:
```bash
/Applications/QuPath.app/Contents/MacOS/QuPath script -c "import net.imglib2.*; print 'Import worked! ' + RealPoint.class"
```
It prints the following
```
OpenJDK 64-Bit Server VM warning: Option --illegal-access is deprecated and will be removed in a future release.
17:40:26.928 [main] [INFO ] qupath.lib.common.ThreadTools - Setting parallelism to 7
17:40:27.099 [main] [INFO ] qupath.ScriptCommand - Setting tile cache size to 2048.00 MB (25.0% max memory)
17:40:27.116 [main] [INFO ] qupath.lib.scripting.QP - Initializing type adapters
17:40:27.603 [main] [INFO ] qupath.lib.gui.ExtensionClassLoader - Refreshing extensions in /Users/myname/QuPath/v0.3/extensions
17:40:27.606 [main] [INFO ] qupath.lib.gui.ExtensionClassLoader - Added extension: /Users/myname/QuPath/v0.3/extensions/imglib2-5.12.0.jar
17:40:27.606 [main] [INFO ] qupath.lib.gui.ExtensionClassLoader - Added extension: /Users/myname/QuPath/v0.3/extensions/qupath-extension-stardist-0.3.0.jar
17:40:27.607 [main] [INFO ] qupath.lib.gui.ExtensionClassLoader - Added extension: /Users/myname/QuPath/v0.3/extensions/qupath-extension-omero-0.3.0.jar
17:40:27.607 [main] [INFO ] qupath.lib.gui.ExtensionClassLoader - Added extension: /Users/myname/QuPath/v0.3/extensions/qupath-extension-align-0.3.0.jar
Import worked! class net.imglib2.RealPoint%   
```

This shows me that the jars were added to the classpath and therefore available to the script.

I haven't tested it on Windows to know if there is any difference (I wouldn't expect any), but I also haven't tried the specific script here so I don't know if there is some more subtle classpath issue somewhere.

**Comment by petebankhead** [comment]
Oops, I've just seen you're using QuPath v0.2.3. I tested only with v0.3.0. It's quite possible that there was an issue and it has now been fixed.

Edit: See reference to command line/classloader improvements in the changelog - https://github.com/qupath/qupath/blob/main/CHANGELOG.md#enhancements

**Comment by NicoKiaru** [comment]
Cleaning issues of archived repos
